spring:
  application:
    name: worldle-api

  data:
    redis:
      url: ${REDIS_URL:redis://localhost:6379}

  web:
    resources:
      add-mappings: false

server:
  port: ${PORT:8080}

admin:
  auth:
    username: ${ADMIN_USERNAME:bot}
    password: ${ADMIN_PASSWORD:bot}

discord:
  bot:
    token: ${DISCORD_BOT_TOKEN}

integration:
  google-maps:
    api-key: ${GOOGLE_MAPS_API_KEY}

  uploadcare:
    public-key: ${UPLOADCARE_PUBLIC_KEY}
    secret-key: ${UPLOADCARE_SECRET_KEY}
