spring:
  application:
    name: worldle-api

  data:
    redis:
      url: ${REDIS_URL:redis://localhost:6379}

bot:
  auth:
    username: ${BOT_USERNAME:bot}
    password: ${BOT_PASSWORD:bot}

integration:
  google-maps:
    api-key: ${GOOGLE_MAPS_API_KEY}

  uploadcare:
    public-key: ${UPLOADCARE_PUBLIC_KEY}
    secret-key: ${UPLOADCARE_SECRET_KEY}
