name: Build API Docker image

on:
  push:
    paths:
      - api/**
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        working-directory: ./api
        run: ./gradlew bootBuildImage

      - name: Push Docker image to container registry
        run: docker push ghcr.io/jirkavrba/worldle/api:latest
